config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  get "search" => "searches#search"

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :relationships, only: [] do
      member do
        get :followings
        get :followers
      end
    end
    resources :reviews, only: [:index, :show, :edit, :update]
    resources :review_comments, only: [:index, :destroy]
    resources :reports, only: [:index, :edit, :update]
    root to: 'homes#top'
  end

  scope module: :public do
    # 退会確認画面
    get  '/customers/check' => 'customers#check'
    # 論理削除用のルーティング
    patch  '/customers/withdraw' => 'customers#withdraw'
    resources :customers, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
        get "followings" => "relationships#followings", as: "followings"
        get "followers" => "relationships#followers", as: "followers"
        member do
          get :favorite_index
        end
    end
    resources :reviews do
      resource :favorites, only: [:create, :destroy]
      resources :review_comments, only: [:create, :destroy]
      resource :reports, only: [:new, :create]
      get :complete, on: :member
    end
    resources :tags, only: [:index]
    resources :taggings
    root to: 'homes#top'
    get "search_tag" => "reviews#search_tag"
    get 'about' => 'homes#about', as: 'about'
  end

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :reports, dependent: :destroy

  #いいね機能
  has_many :favorites, dependent: :destroy

  #コメント機能
  has_many :reviews, dependent: :destroy
  has_many :review_comments, dependent: :destroy

  validates :name, presence: true

  #ゲストログイン機能
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "ゲストユーザー"
    end
  end

  #ActiveStorage
  has_one_attached :image

  def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  #フォロー機能
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follow_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy

  has_many :followings, through: :active_relationships, source: :follower
  has_many :followers, through: :passive_relationships, source: :follow

    #フォローしたときの処理
  def follow(customer)
    active_relationships.create(follower_id: customer.id)
  end

    #フォローを外すときの処理
  def unfollow(customer)
    active_relationships.find_by(follower_id: customer.id).destroy
  end

    #フォローしていればtrueを返す
  def following?(customer)
    followings.include?(customer)
  end

  #ログイン時に退会済みのユーザーが同じアカウントでログイン出来ないようにする
  def active_for_authentication?
    super && (is_active == true)
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
    @spoiler_review = @customer.reviews.where(status: :spoiler)
    @spoiler_not_review = @customer.reviews.where(status: :spoiler_not)
    @draft_review = @customer.reviews.where(status: :draft)
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:admin_customer] = "更新成功"
      redirect_to admin_customer_path(@customer)
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:name,:is_active)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/_side_bar.html.erb
<div class="card p-3">
  <section>
    <div class="flex-row">
      <div class="flex-side_bar">
        <%= image_tag customer.get_image(80,80), class:"rounded-circle" %>
      </div>
      <div class="flex-side_bar">
        <%= link_to "会員情報編集", edit_admin_customer_path(customer.id), class:"btn btn-outline-success mt-2" %>
      </div>
    </div>
  </section>
  <div>
    <p class="mt-2">ユーザー名：<%= customer.name %></p>
  </div>
  <div class="mt-2">
    フォロー：<%= customer.followings.count %>人
    フォロワー：<%= customer.followers.count %>人
  </div>
  <div>
    <p class="mt-2">自己紹介：</p>
    <!--紹介文が「空」のままだとエラーが出るのでnil?=trueの時を追加-->
    <%if customer.introduction.nil? %>
      <%= customer.introduction %>
    <% else %>
      <!--紹介文が「空」じゃない時は正常に反映する-->
      <%= safe_join(customer.introduction.split("\n"),tag(:br)) %>
    <%end %>
  </div>
</div>

app/views/admin/customers/_tab.html.erb
<div class="container">
  <div class="row">
    <div class="col">

      <div class="tabs d-flex justify-content-between align-items-center">
        <ul class="nav nav-tabs">
          <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#notspoiler">ネタバレなし</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#spoiler">ネタバレあり</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#draft">下書き</a>
          </li>
        </ul>
      </div>

      <div class="tab-content">

        <div id="notspoiler" class="tab-pane fade show active">
          <%= render "admin/reviews/spoiler_not_review", spoiler_not_review: @spoiler_not_review %>
        </div>

        <div id="spoiler" class="tab-pane fade">
          <%= render "admin/reviews/spoiler_review", spoiler_review: @spoiler_review %>
        </div>

        <div id="draft" class="tab-pane fade">
          <%= render "admin/reviews/draft_review", draft_review: @draft_review %>
        </div>

      </div>

    </div>
  </div>
</div>

app/views/admin/customers/edit.html.erb
<!--管理者側／会員情報編集画面-->
<div class="container mt-5 py-5">
  <div class="row mx-auto">
    <div class="col-12 offset-lg-3 col-lg-6">
      <div class="card p-5">
      <h3><%= @customer.name %>さんの会員情報編集　</h3>

        <!--会員情報更新失敗のエラーメッセージ-->
        <% if @customer.errors.any? %>
          <div class="alert alert-danger" role="alert">
            <% @customer.errors.full_messages.each do |message| %>
              <p><%= message %></p>
            <% end %>
          </div>
        <% end %>

        <!--会員情報編集フォーム-->
        <%= form_with model: @customer, url: admin_customer_path(@customer), method: :patch do |f| %>
          <table>
            <tbody>
              <tr>
                <td class="p-1">会員ID</td>
                <td class="p-1"><%= @customer.id %></td>
              </tr>
              <tr>
                <td class="p-1">ユーザー名</td>
                <td class="p-1"><%= @customer.name %></td>
              </tr>
              <tr>
                <td class="p-1">メールアドレス</td>
                <td class="p-1"><%= @customer.email %></td>
              </tr>
              <tr>
                <td class="p-1">会員ステータス</td>
                <td class="p-1">
                  <%= f.radio_button :is_active, true %>
      　           <%= f.label :is_active_true, "有効" %>
      　           <%= f.radio_button :is_active, false %>
      　           <%= f.label :is_active_false,"退会" %>
    　          </td>
              </tr>
              <tr>
                <td class="p-2"><%= f.submit "変更を保存", class:"btn btn-outline-success" %></td>
              </tr>
            </tbody>
          </table>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12 offset-lg-1 col-lg-10">
      <h3>会員一覧</h3>

      <section>
        <% @customers.each do |customer| %>
        <div class="flex-row">
          <div class="flex-item">
            <%= image_tag customer.get_image(80,80), class:"rounded-circle" %>
          </div>
          <div class="flex-item">
            <%= link_to admin_customer_path(customer.id) do %>
              <%= customer.name %>
            <% end %>
          </div>
          <div class="flex-item">
            フォロー<%= customer.followings.count %>人
          </div>
          <div class="flex-item">
            フォロワー<%= customer.followers.count %>人
          </div>
          <div class="flex-item <%= customer.is_active ? 'text-success' : 'text-muted' %>">
            <%= customer.is_active ? '有効' : '退会' %>
          </div>
        </div>
        <% end %>
      </section>

      <div class="mx-auto">
        <div class="pagination">
          <%= paginate @customers %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container-fluid">
  <div class="row mt-5">
    <div class="col-12 col-lg-3">
      <%= render 'admin/customers/side_bar', customer: @customer,reviews: @reviews %>
    </div>
    <div class="col-12 col-lg-9">
      <%= render 'admin/customers/tab', spoiler_review: @spoiler_review,spoier_not_review: @spoiler_not_review, draft_review: @draft_review %>
    </div>
  </div>
</div>