config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  get "search" => "searches#search"

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :relationships, only: [] do
      member do
        get :followings
        get :followers
      end
    end
    resources :reviews, only: [:index, :show, :edit, :update]
    resources :review_comments, only: [:index, :destroy]
    resources :reports, only: [:index, :edit, :update]
    root to: 'homes#top'
  end

  scope module: :public do
    # 退会確認画面
    get  '/customers/check' => 'customers#check'
    # 論理削除用のルーティング
    patch  '/customers/withdraw' => 'customers#withdraw'
    resources :customers, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
        get "followings" => "relationships#followings", as: "followings"
        get "followers" => "relationships#followers", as: "followers"
        member do
          get :favorite_index
        end
    end
    resources :reviews do
      resource :favorites, only: [:create, :destroy]
      resources :review_comments, only: [:create, :destroy]
      resource :reports, only: [:new, :create]
      get :complete, on: :member
    end
    resources :tags, only: [:index]
    resources :taggings
    root to: 'homes#top'
    get "search_tag" => "reviews#search_tag"
    get 'about' => 'homes#about', as: 'about'
  end

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :reports, dependent: :destroy

  #いいね機能
  has_many :favorites, dependent: :destroy

  #コメント機能
  has_many :reviews, dependent: :destroy
  has_many :review_comments, dependent: :destroy

  validates :name, presence: true

  #ゲストログイン機能
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "ゲストユーザー"
    end
  end

  #ActiveStorage
  has_one_attached :image

  def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  #フォロー機能
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follow_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy

  has_many :followings, through: :active_relationships, source: :follower
  has_many :followers, through: :passive_relationships, source: :follow

    #フォローしたときの処理
  def follow(customer)
    active_relationships.create(follower_id: customer.id)
  end

    #フォローを外すときの処理
  def unfollow(customer)
    active_relationships.find_by(follower_id: customer.id).destroy
  end

    #フォローしていればtrueを返す
  def following?(customer)
    followings.include?(customer)
  end

  #ログイン時に退会済みのユーザーが同じアカウントでログイン出来ないようにする
  def active_for_authentication?
    super && (is_active == true)
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
    
  belongs_to :customer
  belongs_to :review
  
  validates :customer_id, uniqueness: {scope: :review_id}
    
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follow, class_name: "Customer"
  belongs_to :follower, class_name: "Customer"
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :customer
  belongs_to :review

  enum report_status: { wait: 0, hold: 1, complet: 2 }

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :customer
  has_many :review_comments, dependent: :destroy
  has_many :reports, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  validates :venue_name, presence: true
  validates :status, presence: true

  # ActiveStorage
  has_many_attached :review_images

  def get_review_image(width,height)
    unless review_images.attached?
     file_path = Rails.root.join('app/assets/images/no_image.jpg')
     review_images.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
   review_images.(resize: [width, height]).processed
  end

  # いいね機能
  has_many :favorites, dependent: :destroy

  def favorited_by?(customer)
   favorites.exists?(customer_id: customer.id)
  end

  # タグ機能
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  # タグ付けの新規投稿用メソッド
  def save_tags(tags)
    # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = tags - current_tags

    # 古いタグを消す
    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end

    # 新しいタグを保存
    new_tags.each do |new|
      tags = Tag.find_or_create_by(name: new)
      self.tags << tags
    end
  end


  # 検索機能のためのメソッド
  def self.looks(search, word)
    if search == "partial_match"
      @spoiler_reviews= Review.where("title LIKE? OR sub_title LIKE ?", "%#{word}%", "%#{word}%")
      @not_spoiler_reviews= Review.where("title LIKE? OR sub_title LIKE ?", "%#{word}%", "%#{word}%")
    end
  end

  enum status: { spoiler_not: 0, spoiler: 1, draft: 2 }
end

app/models/review_comment.rb
class ReviewComment < ApplicationRecord

  belongs_to :customer
  belongs_to :review

  validates :comment, presence: true, length: { maximum: 300 }

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy, foreign_key: 'tag_id'
  has_many :reviews, through: :taggings

  validates :name, uniqueness: true, presence:true, length:{maximum:50}
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :review
  belongs_to :tag

  validates :review_id, presence: true
  validates :tag_id, presence: true
end

app/controllers/admin/relationships_controller.rb
class Admin::RelationshipsController < ApplicationController
  before_action :authenticate_admin!

  def followings
    @customer = Customer.find_by(id: params[:customer_id])
    @customers = @customer.followings
  end

  def followers
    @customer = Customer.find_by(id: params[:customer_id])
    @customers = @customer.followers
  end

end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    if resource == :admin
      root_path
    elsif resource == :customer
      customer_path(current_customer.id)
    end
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_customer!

  def search
    @range = params[:range]
    @word = params[:word]

    @spoiler_review = Review.looks(params[:search], params[:word]).where(status: :spoiler)
    @spoiler_not_review = Review.looks(params[:search], params[:word]).where(status: :spoiler_not)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/favorites_helper.rb
module Admin::FavoritesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/relationships_helper.rb
module Admin::RelationshipsHelper
end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/relationships/followers.html.erb
<h2><%= @customer.name %>さんのフォロワー一覧</h2>
<% if @customers.exists? %>
  <table class='table'>
    <thead>
      <tr>
        <th>Image</th>
        <th>name</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td>
            <%= link_to admin_customer_path(customer) do %>
              <%= image_tag customer.get_image(50,50) %>
            <% end %>
          </td>
          <td><%= customer.name %></td>
          <td>
            <%= link_to followings_admin_relationship_path(customer) do %>
              <h6>フォロー<%= customer.followings.count %></h6>
            <% end %>
          </td>
          <td>
            <%= link_to followers_admin_relationship_path(customer) do %>
              <h6>フォロワー<%= customer.followers.count %></h6>
            <% end %>
          </td>
          <td>
            <%= link_to "show", admin_customer_path(customer.id) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>フォローされているユーザーはいません</p>
<% end %>

app/views/admin/relationships/followings.html.erb
<h2><%= @customer.name %>さんのフォロー一覧</h2>
<% if @customers.exists? %>
  <table class='table'>
    <thead>
      <tr>
        <th>Image</th>
        <th>name</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td>
            <%= link_to admin_customer_path(customer) do %>
              <%= image_tag customer.get_image(50,50) %>
            <% end %>
          </td>
          <td><%= customer.name %></td>
          <td>
            <%= link_to followings_admin_relationship_pathh(customer) do %>
              <h6>フォロー<%= customer.followings.count %></h6>
            <% end %>
          </td>
          <td>
            <%= link_to followers_admin_relationship_pathh(customer) do %>
              <h6>フォロワー<%= customer.followers.count %></h6>
            <% end %>
          </td>
          <td>
            <%= link_to "show", admin_customer_path(customer.id) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>フォローしているユーザーはいません</p>
<% end %>