config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  get "search" => "searches#search"

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :relationships, only: [] do
      member do
        get :followings
        get :followers
      end
    end
    resources :reviews, only: [:index, :show, :edit, :update]
    resources :review_comments, only: [:index, :destroy]
    resources :reports, only: [:index, :edit, :update]
    root to: 'homes#top'
  end

  scope module: :public do
    # 退会確認画面
    get  '/customers/check' => 'customers#check'
    # 論理削除用のルーティング
    patch  '/customers/withdraw' => 'customers#withdraw'
    resources :customers, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
        get "followings" => "relationships#followings", as: "followings"
        get "followers" => "relationships#followers", as: "followers"
        member do
          get :favorite_index
        end
    end
    resources :reviews do
      resource :favorites, only: [:create, :destroy]
      resources :review_comments, only: [:create, :destroy]
      resource :reports, only: [:new, :create]
      get :complete, on: :member
    end
    resources :tags, only: [:index]
    resources :taggings
    root to: 'homes#top'
    get "search_tag" => "reviews#search_tag"
    get 'about' => 'homes#about', as: 'about'
  end

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :customer
  belongs_to :review

  enum report_status: { wait: 0, hold: 1, complet: 2 }

end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @reports = Report.all.order(created_at: :desc).page(params[:page]).per(10)
    # 絞り込み機能が使用された場合
    if params[:report_status].present?
      # 選択された report_status に基づいて絞り込み
      @reports = @reports.where(reports: { report_status: params[:report_status] })
    end
    @customers = Customer.all
    @spoiler_not_review = Review.where(status: :spoiler_not)
    @spoiler_review = Review.where(status: :spoiler)
  end

  def edit
    @report = Report.find(params[:id])
  end

  def update
    @report = Report.find(params[:id])
    if @report.update(report_params)
      flash[:notice] = "ステータス変更に成功しました。"
      redirect_to admin_reports_path
    else
      flash[:notice] = "ステータス変更に失敗しました。"
      redirect_to admin_review_path(@review.id)
    end
  end

  private

  def report_params
    params.require(:report).permit(:report_status)
  end

end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
end

app/views/admin/reports/_show_index.html.erb
<section class="review-show-bottom">
  <div class="card">
    <div class="card-header">
      <h6>報告一覧  <%= review.reports.count %>件</h6>
    </div>
    <ul class="list-group list-group-flush">
      <% review.reports.each do |report| %>
        <li class="list-group-item">
          <section class="review-show-top">
            <div class="flex-row">
              <div class="review-show-left">
                <%= report.id %>
              </div>

              <div class="report-show-right ml-3">
                <%= image_tag report.customer.get_image(50,50) %>
                <br />
                <%= report.customer.name %>
              </div>

              <div class="report-show-right ml-5">
                <%= report.report %>
              </div>

              <div class="report-show-right ml-5">
                <%= link_to edit_admin_report_path(report.id) do %>
                  <%= report.report_status_i18n %>
                <% end %>
              </div>
            </div>
          </section>
        </li>
      <% end %>
    </ul>
  </div>
</section>

app/views/admin/reports/edit.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col">

      <h3>報告ステータス編集</h3>

        <section class="review-show-top">
          <div class="flex-row">
            <div class="review-show-left">
              <%= image_tag @report.review.customer.get_image(80,80), class:"rounded-circle" %>
              <br />
              <%= @report.review.customer.name %>
            </div>

            <div class="review-show-right ml-3">
              タイトル：<%= @report.review.title %><%= @report.review.sub_title %>
              <br />
              会場名：<%= @report.review.venue_name %>
              <br />
              公演日：<%= @report.review.date&.strftime('%Y/%m/%d') %>
              <br />
              開演時間：<%= @report.review.time&.strftime('%H:%M') %>
            </div>

            <div class="review-show-right ml-5">
              <%= form_with model: @report, url: admin_report_path, method: :patch do |f| %>
                報告ステータス：<%= f.select :report_status,Report.report_statuses.keys.map { |k| [t("enums.report.report_status.#{k}"), k] }, {} %>
                <%= f.submit '更新する', class: "btn btn-outline-success btn-sm mt-2" %>
              <% end %>
            </div>
          </div>
        </section>

        <section class="review-show">
          <div class="row mt-3">
            <div class="col">
              <div class="card">
                <div class="card-header">
                  <h6>感想・考察：</h6>
                </div>
                <div class="card-body">
                  <!--感想考察が「空」のままだとエラーが出るのでnil?=trueの時を追加-->
                  <%if @report.review.body.nil? %>
                    <%= @report.review.body %>
                  <% else %>
                    <!--感想考察が「空」じゃない時は正常に反映する-->
                    <%= safe_join(@report.review.body.split("\n"),tag(:br)) %>
                  <%end %>
                </div>
              </div>
            </div>
          </div>
        </section>

    </div>
  </div>
</div>

app/views/admin/reports/index.html.erb
<div class= "container mt-5">
  <div class="row">
    <div class="col-12 offset-lg-1 col-lg-10">
      <h3>報告一覧</h3>

      <div class="report-search mb-3">
        <%= form_tag admin_reports_path, method: :get do %>
          <%= label_tag 'report_status', '報告ステータス：' %>
          <%= select_tag 'report_status', options_for_select(Report.report_statuses.keys.map { |k| [t("enums.report.report_status.#{k}"), k] }, params[:report_status]), include_blank: true %>
          <%= submit_tag '検索' %>
        <% end %>
      </div>

      <% if @reports.exists? %>

        <section>
          <div class="flex-row report-title">
            <div class="flex-report-id mr-3"></div>
            <div class="flex-report">投稿ユーザー名</div>
            <div class="flex-report">報告ユーザー名</div>
            <div class="flex-report">投稿詳細</div>
            <div class="flex-report">ステータス</div>
            <div class="flex-report">投稿日</div>
            <div class="flex-report">報告日</div>
          </div>

          <% @reports.each do |report| %>
            <div class="flex-row">
              <div class="flex-report-id mr-3">
                <%= report.id %>
              </div>
              <div class="flex-report">
                <%= @customers.find(report.review.customer_id).name %>
              </div>
              <div class="flex-report">
                <%= @customers.find(report.customer_id).name %>
              </div>
              <div class="flex-report">
                <%= link_to "投稿詳細", admin_review_path(report.review_id) %>
              </div>
              <div class="flex-report">
                <%= link_to edit_admin_report_path(report.id) do %>
                  <%= report.report_status_i18n %>
                <% end %>
              </div>
              <div class="flex-report">
                <%= report.review.created_at.strftime('%Y/%m/%d') %>
              </div>
              <div class="flex-report">
              <%= report.created_at.strftime('%Y/%m/%d') %>
              </div>
            </div>
          <% end %>
        </section>
      <% else %>
        <div class="draft-text d-flex align-items-center justify-content-center", style="height:250px; margin: auto;">
          報告はありません
        </div>
      <% end %>

      <div class="mx-auto">
        <div class="pagination">
          <%= paginate @reports %>
        </div>
      </div>
    </div>
  </div>
</div>