config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  get "search" => "searches#search"

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :relationships, only: [] do
      member do
        get :followings
        get :followers
      end
    end
    resources :reviews, only: [:index, :show, :edit, :update]
    resources :review_comments, only: [:index, :destroy]
    resources :reports, only: [:index, :edit, :update]
    root to: 'homes#top'
  end

  scope module: :public do
    # 退会確認画面
    get  '/customers/check' => 'customers#check'
    # 論理削除用のルーティング
    patch  '/customers/withdraw' => 'customers#withdraw'
    resources :customers, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
        get "followings" => "relationships#followings", as: "followings"
        get "followers" => "relationships#followers", as: "followers"
        member do
          get :favorite_index
        end
    end
    resources :reviews do
      resource :favorites, only: [:create, :destroy]
      resources :review_comments, only: [:create, :destroy]
      resource :reports, only: [:new, :create]
      get :complete, on: :member
    end
    resources :tags, only: [:index]
    resources :taggings
    root to: 'homes#top'
    get "search_tag" => "reviews#search_tag"
    get 'about' => 'homes#about', as: 'about'
  end

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :reports, dependent: :destroy

  #いいね機能
  has_many :favorites, dependent: :destroy

  #コメント機能
  has_many :reviews, dependent: :destroy
  has_many :review_comments, dependent: :destroy

  validates :name, presence: true

  #ゲストログイン機能
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "ゲストユーザー"
    end
  end

  #ActiveStorage
  has_one_attached :image

  def get_image(width,height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  #フォロー機能
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follow_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy

  has_many :followings, through: :active_relationships, source: :follower
  has_many :followers, through: :passive_relationships, source: :follow

    #フォローしたときの処理
  def follow(customer)
    active_relationships.create(follower_id: customer.id)
  end

    #フォローを外すときの処理
  def unfollow(customer)
    active_relationships.find_by(follower_id: customer.id).destroy
  end

    #フォローしていればtrueを返す
  def following?(customer)
    followings.include?(customer)
  end

  #ログイン時に退会済みのユーザーが同じアカウントでログイン出来ないようにする
  def active_for_authentication?
    super && (is_active == true)
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
    
  belongs_to :customer
  belongs_to :review
  
  validates :customer_id, uniqueness: {scope: :review_id}
    
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follow, class_name: "Customer"
  belongs_to :follower, class_name: "Customer"
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :customer
  belongs_to :review

  enum report_status: { wait: 0, hold: 1, complet: 2 }

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :customer
  has_many :review_comments, dependent: :destroy
  has_many :reports, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  validates :venue_name, presence: true
  validates :status, presence: true

  # ActiveStorage
  has_many_attached :review_images

  def get_review_image(width,height)
    unless review_images.attached?
     file_path = Rails.root.join('app/assets/images/no_image.jpg')
     review_images.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
   review_images.(resize: [width, height]).processed
  end

  # いいね機能
  has_many :favorites, dependent: :destroy

  def favorited_by?(customer)
   favorites.exists?(customer_id: customer.id)
  end

  # タグ機能
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  # タグ付けの新規投稿用メソッド
  def save_tags(tags)
    # タグが存在していれば、タグの名前を配列として全て取得
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    # 現在取得したタグから送られてきたタグを除いてoldtagとする
    old_tags = current_tags - tags
    # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
    new_tags = tags - current_tags

    # 古いタグを消す
    old_tags.each do |old|
      self.tags.delete Tag.find_by(name: old)
    end

    # 新しいタグを保存
    new_tags.each do |new|
      tags = Tag.find_or_create_by(name: new)
      self.tags << tags
    end
  end


  # 検索機能のためのメソッド
  def self.looks(search, word)
    if search == "partial_match"
      @spoiler_reviews= Review.where("title LIKE? OR sub_title LIKE ?", "%#{word}%", "%#{word}%")
      @not_spoiler_reviews= Review.where("title LIKE? OR sub_title LIKE ?", "%#{word}%", "%#{word}%")
    end
  end

  enum status: { spoiler_not: 0, spoiler: 1, draft: 2 }
end

app/models/review_comment.rb
class ReviewComment < ApplicationRecord

  belongs_to :customer
  belongs_to :review

  validates :comment, presence: true, length: { maximum: 300 }

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy, foreign_key: 'tag_id'
  has_many :reviews, through: :taggings

  validates :name, uniqueness: true, presence:true, length:{maximum:50}
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :review
  belongs_to :tag

  validates :review_id, presence: true
  validates :tag_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    if resource == :admin
      root_path
    elsif resource == :customer
      customer_path(current_customer.id)
    end
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_customer!

  def search
    @range = params[:range]
    @word = params[:word]

    @spoiler_review = Review.looks(params[:search], params[:word]).where(status: :spoiler)
    @spoiler_not_review = Review.looks(params[:search], params[:word]).where(status: :spoiler_not)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/favorites_helper.rb
module Admin::FavoritesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light header">
  <%= link_to root_path do %>
    <%= image_tag 'Portfolio_logo.png', size: '180x70' %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <div>
      <div class="row header-nav">
        <ul class="navbar-nav ml-auto">
          <% if admin_signed_in? %>
            <li class="nav-item dropdown mx-3">
              <a class="nav-link dropdown-toggle link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa-solid fa-list link"></i>
                <span class="link">一覧</span>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to '会員一覧', admin_customers_path, class: "dropdown-item" %>
                <%= link_to '投稿一覧', admin_reviews_path, class: "dropdown-item" %>
                <%= link_to 'コメント一覧', admin_review_comments_path, class: "dropdown-item" %>
                <%= link_to '報告一覧', admin_reports_path, class: "dropdown-item" %>
              </div>
            </li>
            <li class="nav-item mx-3 mt-2">
              <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: "link" do %>
                <i class="fa-solid fa-right-from-bracket"></i>
              <% end %>
            </li>
          <% elsif customer_signed_in? %>
            <div class="mt-3 mr-5">
              ようこそ、<%= current_customer.name %>さん!
            </div>
            <!--<li class="nav-item mx-3">-->
            <!--  <%#= link_to 'マイページ', customer_path(current_customer.id), class: "btn btn-outline-info" %>-->
            <!--</li>-->
            <li class="nav-item dropdown mx-3">
              <a class="nav-link dropdown-toggle link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa-solid fa-user link"></i>
                <span class="link">マイページ</span>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to 'マイページ', customer_path(current_customer.id), class: "dropdown-item" %>
                <% if current_customer.email != "guest@example.com" %>
                  <%= link_to '会員情報編集', edit_customer_path(current_customer.id), class: "dropdown-item" %>
                <% end %>
                <%= link_to 'フォロー一覧', customer_followings_path(current_customer.id), class: "dropdown-item" %>
                <%= link_to 'フォロワー一覧', customer_followers_path(current_customer.id), class: "dropdown-item" %>
                <%= link_to 'ブックマーク一覧', favorite_index_customer_path(current_customer), class: "dropdown-item" %>
              </div>
            </li>
            <li class="nav-item mx-3 mt-2">
              <%= link_to customers_path, class: "link" do %>
                <i class="fa-solid fa-users"></i> 会員一覧
              <% end %>
            </li>
            <li class="nav-item mx-3 mt-2">
              <%= link_to reviews_path, class: "link" do %>
                <i class="fa-solid fa-list"></i> 投稿一覧
              <% end %>
            </li>
            <li class="nav-item mx-3 mt-2">
              <%= link_to new_review_path, class:"link" do %>
                <i class="fa-solid fa-plus"></i> 新規投稿
              <% end %>
            </li>
            <li class="nav-item mx-3 mt-2">
              <%= link_to destroy_customer_session_path, method: :delete, class: "link" do %>
                <i class="fa-solid fa-right-from-bracket"></i> ログアウト
              <% end %>
            </li>
          <% else %>
            <li class="nav-item mx-3 mt-2">
              <%= link_to new_customer_registration_path, class: "link" do %>
                <i class="fa-solid fa-plus"></i> 新規登録
              <% end %>
            </li>
            <li class="nav-item mx-3 mt-2">
              <%= link_to new_customer_session_path, class: "link" do %>
                <i class="fa-solid fa-right-to-bracket"></i> ログイン
              <% end %>
            </li>
            <li class="nav-item mx-3 mt-2">
              <%= link_to customers_guest_sign_in_path, method: :post, class: "link" do %>
                <i class="fa-solid fa-right-to-bracket"></i> ゲストログイン（閲覧用）
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="row header-search">
        <%= render 'layouts/search' %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_search.html.erb
<% if customer_signed_in? %>
<div class="search_form">
  <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word, placeholder: "タイトル名で検索" %>
      <%= f.hidden_field :range, :value => 'Review' %>
      <%= f.hidden_field :search, :value => "partial_match" %>
      <%= f.submit "検索", class: "btn-sm btn-outline-info" %>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spotlight Reviews</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/3a0ef0e5bc.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <%= render 'layouts/header' %>
    </div>

    <div class="main">
      <div class="notice alert-danger"><%#= notice %></div>
      <!--成功時のアラートメッセージ-->
      <% if flash[:success] %>
      <div class="alert alert-success">
        <%= flash[:success] %>
      </div>
      <% end %>
      <!--失敗時のアラートメッセージ-->
      <% if flash[:danger] %>
      <div class="alert alert-danger">
        <%= flash[:danger] %>
      </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>